/** Cloud Translation NMT languages. https://docs.cloud.google.com/translate/docs/languages */
export type TranslateLanguage = {
    id: string
    name: string
}

export const translateLanguages: readonly TranslateLanguage[] = [
    { id: 'ab', name: 'Abkhaz' },
    { id: 'ace', name: 'Acehnese' },
    { id: 'ach', name: 'Acholi' },
    { id: 'af', name: 'Afrikaans' },
    { id: 'sq', name: 'Albanian' },
    { id: 'alz', name: 'Alur' },
    { id: 'am', name: 'Amharic' },
    { id: 'ar', name: 'Arabic' },
    { id: 'hy', name: 'Armenian' },
    { id: 'as', name: 'Assamese' },
    { id: 'awa', name: 'Awadhi' },
    { id: 'ay', name: 'Aymara' },
    { id: 'az', name: 'Azerbaijani' },
    { id: 'ban', name: 'Balinese' },
    { id: 'bm', name: 'Bambara' },
    { id: 'ba', name: 'Bashkir' },
    { id: 'eu', name: 'Basque' },
    { id: 'btx', name: 'Batak Karo' },
    { id: 'bts', name: 'Batak Simalungun' },
    { id: 'bbc', name: 'Batak Toba' },
    { id: 'be', name: 'Belarusian' },
    { id: 'bem', name: 'Bemba' },
    { id: 'bn', name: 'Bengali' },
    { id: 'bew', name: 'Betawi' },
    { id: 'bho', name: 'Bhojpuri' },
    { id: 'bik', name: 'Bikol' },
    { id: 'bs', name: 'Bosnian' },
    { id: 'br', name: 'Breton' },
    { id: 'bg', name: 'Bulgarian' },
    { id: 'bua', name: 'Buryat' },
    { id: 'yue', name: 'Cantonese' },
    { id: 'ca', name: 'Catalan' },
    { id: 'ceb', name: 'Cebuano' },
    { id: 'ny', name: 'Chichewa (Nyanja)' },
    { id: 'zh-CN', name: 'Chinese (Simplified)' },
    { id: 'zh-TW', name: 'Chinese (Traditional)' },
    { id: 'cv', name: 'Chuvash' },
    { id: 'co', name: 'Corsican' },
    { id: 'crh', name: 'Crimean Tatar' },
    { id: 'hr', name: 'Croatian' },
    { id: 'cs', name: 'Czech' },
    { id: 'da', name: 'Danish' },
    { id: 'din', name: 'Dinka' },
    { id: 'dv', name: 'Divehi' },
    { id: 'doi', name: 'Dogri' },
    { id: 'dov', name: 'Dombe' },
    { id: 'nl', name: 'Dutch' },
    { id: 'dz', name: 'Dzongkha' },
    { id: 'en', name: 'English' },
    { id: 'eo', name: 'Esperanto' },
    { id: 'et', name: 'Estonian' },
    { id: 'ee', name: 'Ewe' },
    { id: 'fj', name: 'Fijian' },
    { id: 'fil', name: 'Filipino (Tagalog)' },
    { id: 'fi', name: 'Finnish' },
    { id: 'fr', name: 'French' },
    { id: 'fr-FR', name: 'French (French)' },
    { id: 'fr-CA', name: 'French (Canadian)' },
    { id: 'fy', name: 'Frisian' },
    { id: 'ff', name: 'Fulfulde' },
    { id: 'gaa', name: 'Ga' },
    { id: 'gl', name: 'Galician' },
    { id: 'lg', name: 'Ganda (Luganda)' },
    { id: 'ka', name: 'Georgian' },
    { id: 'de', name: 'German' },
    { id: 'el', name: 'Greek' },
    { id: 'gn', name: 'Guarani' },
    { id: 'gu', name: 'Gujarati' },
    { id: 'ht', name: 'Haitian Creole' },
    { id: 'cnh', name: 'Hakha Chin' },
    { id: 'ha', name: 'Hausa' },
    { id: 'haw', name: 'Hawaiian' },
    { id: 'iw', name: 'Hebrew' },
    { id: 'hil', name: 'Hiligaynon' },
    { id: 'hi', name: 'Hindi' },
    { id: 'hmn', name: 'Hmong' },
    { id: 'hu', name: 'Hungarian' },
    { id: 'hrx', name: 'Hunsrik' },
    { id: 'is', name: 'Icelandic' },
    { id: 'ig', name: 'Igbo' },
    { id: 'ilo', name: 'Iloko' },
    { id: 'id', name: 'Indonesian' },
    { id: 'ga', name: 'Irish' },
    { id: 'it', name: 'Italian' },
    { id: 'ja', name: 'Japanese' },
    { id: 'jw', name: 'Javanese' },
    { id: 'kn', name: 'Kannada' },
    { id: 'pam', name: 'Kapampangan' },
    { id: 'kk', name: 'Kazakh' },
    { id: 'km', name: 'Khmer' },
    { id: 'cgg', name: 'Kiga' },
    { id: 'rw', name: 'Kinyarwanda' },
    { id: 'ktu', name: 'Kituba' },
    { id: 'gom', name: 'Konkani' },
    { id: 'ko', name: 'Korean' },
    { id: 'kri', name: 'Krio' },
    { id: 'ku', name: 'Kurdish (Kurmanji)' },
    { id: 'ckb', name: 'Kurdish (Sorani)' },
    { id: 'ky', name: 'Kyrgyz' },
    { id: 'lo', name: 'Lao' },
    { id: 'ltg', name: 'Latgalian' },
    { id: 'la', name: 'Latin' },
    { id: 'lv', name: 'Latvian' },
    { id: 'lij', name: 'Ligurian' },
    { id: 'li', name: 'Limburgan' },
    { id: 'ln', name: 'Lingala' },
    { id: 'lt', name: 'Lithuanian' },
    { id: 'lmo', name: 'Lombard' },
    { id: 'luo', name: 'Luo' },
    { id: 'lb', name: 'Luxembourgish' },
    { id: 'mk', name: 'Macedonian' },
    { id: 'mai', name: 'Maithili' },
    { id: 'mak', name: 'Makassar' },
    { id: 'mg', name: 'Malagasy' },
    { id: 'ms', name: 'Malay' },
    { id: 'ms-Arab', name: 'Malay (Jawi)' },
    { id: 'ml', name: 'Malayalam' },
    { id: 'mt', name: 'Maltese' },
    { id: 'mi', name: 'Maori' },
    { id: 'mr', name: 'Marathi' },
    { id: 'chm', name: 'Meadow Mari' },
    { id: 'mni-Mtei', name: 'Meiteilon (Manipuri)' },
    { id: 'min', name: 'Minang' },
    { id: 'lus', name: 'Mizo' },
    { id: 'mn', name: 'Mongolian' },
    { id: 'my', name: 'Myanmar (Burmese)' },
    { id: 'nr', name: 'Ndebele (South)' },
    { id: 'new', name: 'Nepalbhasa (Newari)' },
    { id: 'ne', name: 'Nepali' },
    { id: 'nso', name: 'Northern Sotho (Sepedi)' },
    { id: 'no', name: 'Norwegian' },
    { id: 'nus', name: 'Nuer' },
    { id: 'oc', name: 'Occitan' },
    { id: 'or', name: 'Odia (Oriya)' },
    { id: 'om', name: 'Oromo' },
    { id: 'pag', name: 'Pangasinan' },
    { id: 'pap', name: 'Papiamento' },
    { id: 'ps', name: 'Pashto' },
    { id: 'fa', name: 'Persian' },
    { id: 'pl', name: 'Polish' },
    { id: 'pt', name: 'Portuguese' },
    { id: 'pt-PT', name: 'Portuguese (Portugal)' },
    { id: 'pt-BR', name: 'Portuguese (Brazil)' },
    { id: 'pa', name: 'Punjabi' },
    { id: 'pa-Arab', name: 'Punjabi (Shahmukhi)' },
    { id: 'qu', name: 'Quechua' },
    { id: 'rom', name: 'Romani' },
    { id: 'ro', name: 'Romanian' },
    { id: 'rn', name: 'Rundi' },
    { id: 'ru', name: 'Russian' },
    { id: 'sm', name: 'Samoan' },
    { id: 'sg', name: 'Sango' },
    { id: 'sa', name: 'Sanskrit' },
    { id: 'gd', name: 'Scots Gaelic' },
    { id: 'sr', name: 'Serbian' },
    { id: 'st', name: 'Sesotho' },
    { id: 'crs', name: 'Seychellois Creole' },
    { id: 'shn', name: 'Shan' },
    { id: 'sn', name: 'Shona' },
    { id: 'scn', name: 'Sicilian' },
    { id: 'szl', name: 'Silesian' },
    { id: 'sd', name: 'Sindhi' },
    { id: 'si', name: 'Sinhala (Sinhalese)' },
    { id: 'sk', name: 'Slovak' },
    { id: 'sl', name: 'Slovenian' },
    { id: 'so', name: 'Somali' },
    { id: 'es', name: 'Spanish' },
    { id: 'su', name: 'Sundanese' },
    { id: 'sw', name: 'Swahili' },
    { id: 'ss', name: 'Swati' },
    { id: 'sv', name: 'Swedish' },
    { id: 'tg', name: 'Tajik' },
    { id: 'ta', name: 'Tamil' },
    { id: 'tt', name: 'Tatar' },
    { id: 'te', name: 'Telugu' },
    { id: 'tet', name: 'Tetum' },
    { id: 'th', name: 'Thai' },
    { id: 'ti', name: 'Tigrinya' },
    { id: 'ts', name: 'Tsonga' },
    { id: 'tn', name: 'Tswana' },
    { id: 'tr', name: 'Turkish' },
    { id: 'tk', name: 'Turkmen' },
    { id: 'ak', name: 'Twi (Akan)' },
    { id: 'uk', name: 'Ukrainian' },
    { id: 'ur', name: 'Urdu' },
    { id: 'ug', name: 'Uyghur' },
    { id: 'uz', name: 'Uzbek' },
    { id: 'vi', name: 'Vietnamese' },
    { id: 'cy', name: 'Welsh' },
    { id: 'xh', name: 'Xhosa' },
    { id: 'yi', name: 'Yiddish' },
    { id: 'yo', name: 'Yoruba' },
    { id: 'yua', name: 'Yucatec Maya' },
    { id: 'zu', name: 'Zulu' },
]

const translateLanguageNames = new Map(translateLanguages.map((language) => [language.id, language.name]))

/** Codes a profile may store for a language listed under another id. */
const translateLanguageAliases: Record<string, string> = {
    he: 'iw',
    jv: 'jw',
    tl: 'fil',
    zh: 'zh-CN',
}

export function translateLanguageName(languageId: string): string {
    const alias = translateLanguageAliases[languageId]
    return (
        translateLanguageNames.get(languageId) ?? (alias ? translateLanguageNames.get(alias) : undefined) ?? languageId
    )
}

export function resolveTranslateLanguageId(languageId: string | null | undefined): string | null {
    if (!languageId) return null
    if (translateLanguageNames.has(languageId)) return languageId
    const alias = translateLanguageAliases[languageId]
    if (alias && translateLanguageNames.has(alias)) return alias
    return null
}
